import {
  ArrowUpDown,
  Bike,
  Building2,
  Camera,
  Car,
  Droplets,
  Flame,
  Home,
  KeyRound,
  Layers,
  Package,
  Phone,
  Shield,
  Sparkles,
  Sun,
  Thermometer,
  TreePine,
  Truck,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
  Zap,
  Dumbbell,
  Wine,
  Plane,
  Leaf,
  MapPin,
  Warehouse,
} from 'lucide-react'

const DEFAULT_ICON = Sparkles

export const OAP_AMENITY_ICONS = {
  underground_parking: Car,
  covered_parking: Car,
  bike_storage: Bike,
  storage_room: Package,
  security_24_7: Shield,
  cctv: Camera,
  video_intercom: Phone,
  elevator: ArrowUpDown,
  air_conditioning: Wind,
  fireplace: Flame,
  smart_home: Home,
  solar_panels: Sun,
  fibre_internet: Wifi,
  pool: Waves,
  pool_private: Waves,
  pool_communal: Waves,
  parking: Car,
  garage: Car,
  sea_view: Waves,
  garden: TreePine,
  balcony: Building2,
  rooftop_terrace: Sun,
  private_garage: Car,
  open_parking: Car,
  sauna: Thermometer,
  spa: Sparkles,
  spa_wellness: Sparkles,
  surface_parking: Car,
  ev_charging: Zap,
  loading_dock: Truck,
  raised_floor: Layers,
  hvac_system: Wind,
  three_phase_power: Zap,
  backup_generator: Zap,
  access_control: KeyRound,
  freight_elevator: ArrowUpDown,
  electricity_connected: Zap,
  internet_connected: Wifi,
  water_connected: Droplets,
  gas_connected: Flame,
  sewage_connected: Droplets,
  road_access_paved: MapPin,
  road_access_dirt: MapPin,
  sea_frontage: Waves,
  trees_on_plot: TreePine,
  existing_structures: Warehouse,
  gym: Dumbbell,
  tennis_court: Sparkles,
  restaurant: UtensilsCrossed,
  bar_lounge: Wine,
  parking_onsite: Car,
  helipad: Plane,
  smart_building_bms: Home,
  energy_certificate: Leaf,
}

export function getAmenityIcon(tzKey) {
  return OAP_AMENITY_ICONS[tzKey] || DEFAULT_ICON
}
