import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const source = await readFile(new URL('./TestDriveLandingPage.jsx', import.meta.url), 'utf8')
const css = await readFile(new URL('./TestDriveLandingPage.css', import.meta.url), 'utf8')

test('mobile test-drive landing keeps the commercial buyer hierarchy', () => {
  assert.match(source, /BuyerEmptyState/)
  assert.match(source, /const PAGE_SIZE = 16/)
  assert.match(source, /className="test-drive-hero-card"/)
  assert.match(source, /Поживите здесь до покупки/)
  assert.doesNotMatch(source, /Проверьте дом, район и ритм жизни/)
  assert.match(source, /Марбелья, Испания/)
  assert.match(source, /12 авг — 18 авг/)
  assert.match(source, /Найти свободные объекты/)
  assert.match(source, /const scrollToCatalog = \(\) =>/)
  assert.match(source, /scrollIntoView\(\{ behavior: 'smooth', block: 'start' \}\)/)
  assert.match(source, /<Link to="\/profile\/bookings"/)
  assert.match(source, /<FiMenu size=\{20\}/)
  assert.match(source, /to="\/sections"/)
  assert.match(source, /className="test-drive-hero__search-capsule"/)
  assert.match(source, />\s*\u041f\u043e\u0438\u0441\u043a \u0442\u0435\u0441\u0442-\u0434\u0440\u0430\u0439\u0432\u0430\s*</)
  assert.match(source, /className="test-drive-hero__utility test-drive-hero__utility--profile"/)
  assert.doesNotMatch(source, />\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e</)
  assert.doesNotMatch(source, /test-drive-hero-card__bookings/)
  assert.doesNotMatch(source, /<span>Направление<\/span>/)
  assert.doesNotMatch(source, /<span>Даты<\/span>/)
  assert.match(source, /test-drive-hero__copy test-drive-hero__copy--desktop/)
  assert.match(source, /\u0422\u0435\u0441\u0442-\u0434\u0440\u0430\u0439\u0432 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438/)
  assert.match(source, /\u041c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0439 \u043e\u0442\u043f\u0443\u0441\u043a \u043f\u0435\u0440\u0435\u0434 \u043f\u043e\u043a\u0443\u043f\u043a\u043e\u0439/)
  assert.match(source, /test-drive-hero__copy test-drive-hero__copy--mobile/)
  assert.match(source, /HERO_MOBILE_IMAGE/)
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.test-drive-hero__shade/)
  assert.match(css, /\.test-drive-hero__copy--mobile\s*\{[\s\S]*display:\s*none/)
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.test-drive-hero__copy--desktop\s*\{[\s\S]*display:\s*none/)
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.test-drive-hero__copy--mobile\s*\{[\s\S]*display:\s*block/)
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.test-drive-hero\s*\{[\s\S]*border-radius:\s*0 0 50% 50%/)
  assert.match(css, /\.test-drive-hero__search-capsule[\s\S]*background:\s*rgba\(255, 255, 255, 0\.14\)/)
})

test('test-drive cards preserve touch and type readability on phones', () => {
  assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.test-drive-card__favorite[\s\S]*width:\s*44px[\s\S]*height:\s*44px/)
  assert.match(css, /\.test-drive-card-grid[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.doesNotMatch(css, /@media \(max-width: 374px\)[\s\S]*grid-template-columns:\s*1fr/)
  assert.match(css, /\.test-drive-landing \.listing-page-pagination[\s\S]*\.auction-desktop-pagination__page[\s\S]*min-width:\s*44px[\s\S]*height:\s*44px/)
  assert.match(css, /\.test-drive-hero-card__action[\s\S]*min-height:\s*52px/)
  assert.match(css, /\.test-drive-hero-card\s*\{[\s\S]*width:\s*min\(100%, 330px\)/)
  assert.match(css, /:focus-visible/)
  assert.match(css, /:focus-within/)
})

test('test-drive catalogue keeps truthful counts and accessible card states', () => {
  assert.doesNotMatch(source, /filteredListings\.length \|\| listings\.length/)
  assert.match(source, /favoriteActive \? 'Убрать из избранного' : 'Добавить в избранное'/)
  assert.match(source, /aria-pressed=\{favoriteActive\}/)
  assert.match(source, /listing\.price != null \?/)
  assert.match(source, /По запросу/)
  assert.match(source, /listing\.bedrooms != null/)
  assert.match(source, /listing\.bathrooms != null/)
  assert.match(source, /listing\.area != null/)
  assert.match(source, /matchesSelectedTestDriveAmenities\(item, selectedAmenities\)/)
  assert.match(source, /matchesSelectedTestDriveDurations\(item, selectedDurations\)/)
  assert.match(source, /paginateTestDriveListings\(filteredListings, safePage/)
  assert.match(source, /usePropertyFavorites/)
  assert.match(source, /isFavorite\(favoriteProperty/)
  assert.match(source, /toggleFavorite\(favoriteProperty/)
  assert.match(source, /ensureCanOpenProperty/)
  assert.match(source, /getPropertyTestDrivePath/)
  assert.match(source, /TEST_DRIVE_CARD_IMAGE_FALLBACK/)
  assert.match(source, /onError=\{handleTestDriveImageError\}/)
  assert.match(source, /listing\.rating != null/)
  assert.match(source, />\u041d\u043e\u0432\u044b\u0439</)
})
