export {
  BUYER_CABINET_WELCOME_IMAGES,
  BUYER_CABINET_WELCOME_IMAGES_FULL,
  BUYER_CABINET_WELCOME_PRESET,
  BUYER_CABINET_WELCOME_PRESET_FULL,
  preloadBuyerCabinetWelcomeImages,
} from './buyerCabinetWelcomePresets'
