// Text shown when the live model is unavailable. Keep all supported interface languages here.
const text = {
  ru: {
    propertyTitle: 'Инвестиционный объект',
    scenarioLow: 'Стресс-сценарий с более высокой вакантностью и слабыми темпами рынка.',
    scenarioBase: 'Базовый сценарий на введённых параметрах с умеренной вакантностью.',
    scenarioHigh: 'Сценарий ускоренного роста при устойчивом спросе и контроле расходов.',
    missingIncome: 'Не указан подтверждённый ежемесячный доход для персональной оценки ипотеки.',
    missingResidence: 'Не указана страна налогового резидентства покупателя.',
    unavailable: 'Актуальные данные AI временно недоступны; показан проверяемый расчётный сценарий.',
    marketFallback: 'Расчёт построен на параметрах пользователя без подтверждённого live-контекста рынка.',
    marketBase: 'Предварительный сценарный анализ выбранного рынка.',
    downPayment: 'Размер первоначального взноса', income: 'Подтверждённый доход', residence: 'Статус резидентства',
    mortgageDisclaimer: 'Предварительная аналитическая оценка. Окончательные условия и решение определяет банк.',
    verdictStrong: 'Сильный потенциал при контроле расходов', verdictBalanced: 'Сбалансированная инвестиционная картина', verdictRisky: 'Запас прочности пока слишком мал',
    verdictSummary: 'Результат зависит прежде всего от цены входа, фактической аренды, вакантности и условий финансирования.',
    horizon: 'Сценарный горизонт', horizonText: (years) => `Прогноз учитывает ${years} лет владения и три режима рынка.`,
    entry: 'Контроль цены входа', entryText: (amount) => `Ориентир для переговоров — около ${amount}.`,
    vacancy: 'Вакантность', vacancyText: 'Периоды без арендатора снижают денежный поток.', vacancyAction: 'Заложить резерв не менее нескольких месячных платежей.',
    rate: 'Ставка и одобрение', rateText: 'Финальная ставка зависит от профиля заёмщика и политики банка.', rateAction: 'Сравнить предварительные решения нескольких кредиторов.',
    priceCap: 'Зафиксировать потолок цены', priceCapAction: (amount) => `Не выходить выше ${amount} без подтверждения более высокой аренды.`, priceCapEffect: 'Повышает запас прочности и потенциальную доходность.',
    rent: 'Подтвердить аренду', rentAction: 'Собрать минимум пять сравнимых актуальных предложений в том же районе.', rentEffect: 'Снижает риск завышенного денежного потока.',
    banks: 'Сравнить решения банков', banksAction: 'Запросить предварительные предложения минимум у двух кредиторов.', banksEffect: 'Покажет реальный LTV, ставку и требования к документам.',
    bankRange: 'Получить банковский диапазон', bankRangeAction: 'Добавить доход, резидентство и текущие обязательства.', bankRangeEffect: 'Позволит уточнить LTV, ставку и ежемесячный платёж.',
  },
  en: {
    propertyTitle: 'Investment property',
    scenarioLow: 'Stress scenario with higher vacancy and weak market growth.', scenarioBase: 'Base scenario using your inputs and moderate vacancy.', scenarioHigh: 'Faster growth scenario with steady demand and controlled costs.',
    missingIncome: 'Verified monthly income was not provided for a personal mortgage estimate.', missingResidence: "The buyer's tax residence country was not provided.", unavailable: 'Live AI data is temporarily unavailable; a verifiable calculation scenario is shown.',
    marketFallback: 'The calculation uses your inputs without verified live market context.', marketBase: 'Preliminary scenario analysis for the selected market.',
    downPayment: 'Down payment size', income: 'Verified income', residence: 'Residency status',
    mortgageDisclaimer: 'Preliminary analytical estimate. The bank determines the final terms and decision.',
    verdictStrong: 'Strong potential if costs are controlled', verdictBalanced: 'Balanced investment outlook', verdictRisky: 'The safety margin is currently too small',
    verdictSummary: 'The result mainly depends on the entry price, actual rent, vacancy and financing terms.',
    horizon: 'Investment horizon', horizonText: (years) => `The forecast covers ${years} years of ownership and three market scenarios.`,
    entry: 'Entry price control', entryText: (amount) => `A negotiation target is around ${amount}.`,
    vacancy: 'Vacancy', vacancyText: 'Periods without a tenant reduce cash flow.', vacancyAction: 'Keep a reserve of at least several monthly payments.',
    rate: 'Rate and approval', rateText: 'The final rate depends on the borrower profile and bank policy.', rateAction: 'Compare preliminary offers from several lenders.',
    priceCap: 'Set a price ceiling', priceCapAction: (amount) => `Do not exceed ${amount} without evidence of higher rent.`, priceCapEffect: 'Improves the safety margin and potential return.',
    rent: 'Verify rental income', rentAction: 'Collect at least five current comparable listings in the same area.', rentEffect: 'Reduces the risk of overstated cash flow.',
    banks: 'Compare bank offers', banksAction: 'Request preliminary offers from at least two lenders.', banksEffect: 'Shows realistic LTV, rates and document requirements.',
    bankRange: 'Get a bank estimate', bankRangeAction: 'Add income, residency and current obligations.', bankRangeEffect: 'Helps refine LTV, rate and monthly payment.',
  },
  de: {
    propertyTitle: 'Investitionsobjekt',
    scenarioLow: 'Stressszenario mit höherem Leerstand und schwachem Marktwachstum.', scenarioBase: 'Basisszenario mit Ihren Angaben und moderatem Leerstand.', scenarioHigh: 'Szenario mit schnellerem Wachstum bei stabiler Nachfrage und kontrollierten Kosten.',
    missingIncome: 'Für eine persönliche Hypothekenschätzung fehlt ein nachgewiesenes Monatseinkommen.', missingResidence: 'Das Land der steuerlichen Ansässigkeit des Käufers fehlt.', unavailable: 'Aktuelle KI-Daten sind vorübergehend nicht verfügbar; ein nachvollziehbares Rechenszenario wird angezeigt.',
    marketFallback: 'Die Berechnung basiert auf Ihren Angaben ohne bestätigte aktuelle Marktdaten.', marketBase: 'Vorläufige Szenarioanalyse für den gewählten Markt.',
    downPayment: 'Höhe der Anzahlung', income: 'Nachgewiesenes Einkommen', residence: 'Aufenthaltsstatus',
    mortgageDisclaimer: 'Vorläufige analytische Schätzung. Über endgültige Konditionen und Zusage entscheidet die Bank.',
    verdictStrong: 'Starkes Potenzial bei kontrollierten Kosten', verdictBalanced: 'Ausgewogene Investitionsaussichten', verdictRisky: 'Der Sicherheitspuffer ist derzeit zu klein',
    verdictSummary: 'Das Ergebnis hängt vor allem vom Kaufpreis, der tatsächlichen Miete, dem Leerstand und den Finanzierungskonditionen ab.',
    horizon: 'Anlagehorizont', horizonText: (years) => `Die Prognose umfasst ${years} Jahre Eigentum und drei Marktszenarien.`,
    entry: 'Kaufpreis kontrollieren', entryText: (amount) => `Ein Verhandlungsziel liegt bei etwa ${amount}.`,
    vacancy: 'Leerstand', vacancyText: 'Zeiten ohne Mieter verringern den Cashflow.', vacancyAction: 'Eine Reserve für mindestens mehrere Monatszahlungen einplanen.',
    rate: 'Zins und Zusage', rateText: 'Der endgültige Zinssatz hängt vom Kreditnehmer und der Bank ab.', rateAction: 'Vorläufige Angebote mehrerer Kreditgeber vergleichen.',
    priceCap: 'Preisobergrenze festlegen', priceCapAction: (amount) => `Ohne Nachweis höherer Miete nicht mehr als ${amount} zahlen.`, priceCapEffect: 'Verbessert Sicherheitspuffer und mögliche Rendite.',
    rent: 'Mieteinnahmen prüfen', rentAction: 'Mindestens fünf aktuelle Vergleichsangebote im selben Gebiet sammeln.', rentEffect: 'Verringert das Risiko eines überschätzten Cashflows.',
    banks: 'Bankangebote vergleichen', banksAction: 'Vorläufige Angebote von mindestens zwei Kreditgebern einholen.', banksEffect: 'Zeigt realistische Beleihung, Zinsen und Dokumentanforderungen.',
    bankRange: 'Bankspanne ermitteln', bankRangeAction: 'Einkommen, Wohnsitz und laufende Verpflichtungen ergänzen.', bankRangeEffect: 'Hilft bei der Einschätzung von Beleihung, Zins und Monatsrate.',
  },
  es: {
    propertyTitle: 'Inmueble de inversión',
    scenarioLow: 'Escenario adverso con más vacancia y menor crecimiento del mercado.', scenarioBase: 'Escenario base con tus datos y vacancia moderada.', scenarioHigh: 'Escenario de crecimiento acelerado con demanda estable y gastos controlados.',
    missingIncome: 'Falta el ingreso mensual acreditado para una estimación hipotecaria personal.', missingResidence: 'Falta el país de residencia fiscal del comprador.', unavailable: 'Los datos actuales de IA no están disponibles temporalmente; se muestra un escenario de cálculo verificable.',
    marketFallback: 'El cálculo usa tus datos sin contexto de mercado actual verificado.', marketBase: 'Análisis preliminar de escenarios para el mercado seleccionado.',
    downPayment: 'Importe de la entrada', income: 'Ingresos acreditados', residence: 'Situación de residencia',
    mortgageDisclaimer: 'Estimación analítica preliminar. El banco determina las condiciones y la decisión finales.',
    verdictStrong: 'Buen potencial si se controlan los gastos', verdictBalanced: 'Perspectiva de inversión equilibrada', verdictRisky: 'El margen de seguridad aún es demasiado pequeño',
    verdictSummary: 'El resultado depende sobre todo del precio de compra, el alquiler real, la vacancia y las condiciones de financiación.',
    horizon: 'Horizonte de inversión', horizonText: (years) => `La previsión cubre ${years} años de propiedad y tres escenarios de mercado.`,
    entry: 'Control del precio de compra', entryText: (amount) => `Un objetivo de negociación ronda los ${amount}.`,
    vacancy: 'Vacancia', vacancyText: 'Los periodos sin inquilino reducen el flujo de caja.', vacancyAction: 'Reserva al menos varios pagos mensuales.',
    rate: 'Tipo y aprobación', rateText: 'El tipo final depende del perfil del prestatario y de la política del banco.', rateAction: 'Compara ofertas preliminares de varios prestamistas.',
    priceCap: 'Fijar un precio máximo', priceCapAction: (amount) => `No superes ${amount} sin pruebas de un alquiler mayor.`, priceCapEffect: 'Mejora el margen de seguridad y la rentabilidad potencial.',
    rent: 'Verificar el alquiler', rentAction: 'Reúne al menos cinco anuncios comparables recientes en la misma zona.', rentEffect: 'Reduce el riesgo de sobrestimar el flujo de caja.',
    banks: 'Comparar ofertas bancarias', banksAction: 'Solicita ofertas preliminares a al menos dos entidades.', banksEffect: 'Muestra una financiación, tipos y requisitos documentales realistas.',
    bankRange: 'Obtener una estimación bancaria', bankRangeAction: 'Añade ingresos, residencia y obligaciones actuales.', bankRangeEffect: 'Ayuda a precisar la financiación, el tipo y la cuota mensual.',
  },
  fr: {
    propertyTitle: 'Bien d’investissement',
    scenarioLow: 'Scénario défavorable avec plus de vacance et une faible croissance du marché.', scenarioBase: 'Scénario de base fondé sur vos données et une vacance modérée.', scenarioHigh: 'Scénario de croissance accélérée avec une demande stable et des coûts maîtrisés.',
    missingIncome: 'Le revenu mensuel vérifié manque pour une estimation hypothécaire personnalisée.', missingResidence: 'Le pays de résidence fiscale de l’acheteur manque.', unavailable: 'Les données IA récentes sont temporairement indisponibles ; un scénario de calcul vérifiable est affiché.',
    marketFallback: 'Le calcul utilise vos données sans contexte de marché récent vérifié.', marketBase: 'Analyse préliminaire de scénarios pour le marché choisi.',
    downPayment: 'Montant de l’apport', income: 'Revenus vérifiés', residence: 'Statut de résidence',
    mortgageDisclaimer: 'Estimation analytique préliminaire. La banque décide des conditions et de l’accord définitifs.',
    verdictStrong: 'Fort potentiel si les coûts sont maîtrisés', verdictBalanced: 'Perspectives d’investissement équilibrées', verdictRisky: 'La marge de sécurité est actuellement trop faible',
    verdictSummary: 'Le résultat dépend surtout du prix d’achat, du loyer réel, de la vacance et des conditions de financement.',
    horizon: 'Horizon d’investissement', horizonText: (years) => `La prévision couvre ${years} ans de détention et trois scénarios de marché.`,
    entry: 'Maîtrise du prix d’achat', entryText: (amount) => `Un objectif de négociation se situe autour de ${amount}.`,
    vacancy: 'Vacance locative', vacancyText: 'Les périodes sans locataire réduisent le flux de trésorerie.', vacancyAction: 'Prévoir une réserve d’au moins plusieurs mensualités.',
    rate: 'Taux et accord', rateText: 'Le taux final dépend du profil de l’emprunteur et de la politique bancaire.', rateAction: 'Comparer les offres préliminaires de plusieurs prêteurs.',
    priceCap: 'Fixer un prix plafond', priceCapAction: (amount) => `Ne pas dépasser ${amount} sans preuve d’un loyer plus élevé.`, priceCapEffect: 'Améliore la marge de sécurité et le rendement potentiel.',
    rent: 'Vérifier les loyers', rentAction: 'Recueillir au moins cinq annonces comparables récentes dans le même quartier.', rentEffect: 'Réduit le risque de surestimer le flux de trésorerie.',
    banks: 'Comparer les offres bancaires', banksAction: 'Demander des offres préliminaires à au moins deux prêteurs.', banksEffect: 'Précise le financement, les taux et les pièces requises.',
    bankRange: 'Obtenir une estimation bancaire', bankRangeAction: 'Ajouter revenus, résidence et dettes actuelles.', bankRangeEffect: 'Aide à préciser le financement, le taux et la mensualité.',
  },
  pl: {
    propertyTitle: 'Nieruchomość inwestycyjna',
    scenarioLow: 'Scenariusz stresowy z większym pustostanem i słabszym wzrostem rynku.', scenarioBase: 'Scenariusz bazowy oparty na podanych danych i umiarkowanym pustostanie.', scenarioHigh: 'Scenariusz szybszego wzrostu przy stabilnym popycie i kontrolowanych kosztach.',
    missingIncome: 'Brakuje potwierdzonego miesięcznego dochodu do indywidualnej oceny kredytu.', missingResidence: 'Nie podano kraju rezydencji podatkowej kupującego.', unavailable: 'Aktualne dane AI są tymczasowo niedostępne; pokazano możliwy do weryfikacji scenariusz obliczeniowy.',
    marketFallback: 'Obliczenie opiera się na Twoich danych bez potwierdzonych bieżących danych rynkowych.', marketBase: 'Wstępna analiza scenariuszowa wybranego rynku.',
    downPayment: 'Wysokość wkładu własnego', income: 'Potwierdzony dochód', residence: 'Status rezydencji',
    mortgageDisclaimer: 'Wstępna ocena analityczna. Ostateczne warunki i decyzję określa bank.',
    verdictStrong: 'Duży potencjał przy kontroli kosztów', verdictBalanced: 'Zrównoważone perspektywy inwestycji', verdictRisky: 'Margines bezpieczeństwa jest obecnie zbyt mały',
    verdictSummary: 'Wynik zależy głównie od ceny zakupu, faktycznego czynszu, pustostanów i warunków finansowania.',
    horizon: 'Horyzont inwestycji', horizonText: (years) => `Prognoza obejmuje ${years} lat własności i trzy scenariusze rynkowe.`,
    entry: 'Kontrola ceny zakupu', entryText: (amount) => `Cel negocjacji to około ${amount}.`,
    vacancy: 'Pustostan', vacancyText: 'Okresy bez najemcy zmniejszają przepływy pieniężne.', vacancyAction: 'Zachowaj rezerwę na co najmniej kilka miesięcznych rat.',
    rate: 'Oprocentowanie i decyzja', rateText: 'Ostateczne oprocentowanie zależy od profilu kredytobiorcy i polityki banku.', rateAction: 'Porównaj wstępne oferty kilku kredytodawców.',
    priceCap: 'Ustal górną cenę', priceCapAction: (amount) => `Nie przekraczaj ${amount} bez potwierdzenia wyższego czynszu.`, priceCapEffect: 'Zwiększa margines bezpieczeństwa i potencjalny zwrot.',
    rent: 'Potwierdź czynsz', rentAction: 'Zbierz co najmniej pięć aktualnych ofert porównywalnych w tej samej okolicy.', rentEffect: 'Zmniejsza ryzyko zawyżenia przepływów pieniężnych.',
    banks: 'Porównaj oferty banków', banksAction: 'Poproś o wstępne oferty co najmniej dwóch kredytodawców.', banksEffect: 'Pokazuje realny poziom finansowania, oprocentowanie i wymagane dokumenty.',
    bankRange: 'Uzyskaj ocenę banku', bankRangeAction: 'Dodaj dochód, rezydencję i bieżące zobowiązania.', bankRangeEffect: 'Pozwala doprecyzować finansowanie, oprocentowanie i miesięczną ratę.',
  },
  sv: {
    propertyTitle: 'Investeringsobjekt',
    scenarioLow: 'Stresscenario med högre vakans och svag marknadstillväxt.', scenarioBase: 'Basscenario utifrån dina uppgifter och måttlig vakans.', scenarioHigh: 'Scenario med snabbare tillväxt, stabil efterfrågan och kontrollerade kostnader.',
    missingIncome: 'Verifierad månadsinkomst saknas för en personlig bolånebedömning.', missingResidence: 'Köparens skatterättsliga hemvist har inte angetts.', unavailable: 'Aktuella AI-data är tillfälligt otillgängliga; ett kontrollerbart beräkningsscenario visas.',
    marketFallback: 'Beräkningen bygger på dina uppgifter utan verifierade aktuella marknadsdata.', marketBase: 'Preliminär scenarioanalys för den valda marknaden.',
    downPayment: 'Kontantinsats', income: 'Verifierad inkomst', residence: 'Bosättningsstatus',
    mortgageDisclaimer: 'Preliminär analytisk uppskattning. Banken avgör slutliga villkor och beslut.',
    verdictStrong: 'Stark potential om kostnaderna hålls nere', verdictBalanced: 'Balanserade investeringsutsikter', verdictRisky: 'Säkerhetsmarginalen är för liten just nu',
    verdictSummary: 'Resultatet beror främst på inköpspris, faktisk hyra, vakans och finansieringsvillkor.',
    horizon: 'Investeringshorisont', horizonText: (years) => `Prognosen omfattar ${years} års ägande och tre marknadsscenarier.`,
    entry: 'Kontroll av inköpspris', entryText: (amount) => `Ett förhandlingsmål är cirka ${amount}.`,
    vacancy: 'Vakans', vacancyText: 'Perioder utan hyresgäst minskar kassaflödet.', vacancyAction: 'Avsätt en buffert för minst flera månadsbetalningar.',
    rate: 'Ränta och godkännande', rateText: 'Den slutliga räntan beror på låntagaren och bankens policy.', rateAction: 'Jämför preliminära erbjudanden från flera långivare.',
    priceCap: 'Sätt ett pristak', priceCapAction: (amount) => `Betala inte mer än ${amount} utan belägg för högre hyra.`, priceCapEffect: 'Förbättrar säkerhetsmarginalen och möjlig avkastning.',
    rent: 'Verifiera hyran', rentAction: 'Samla minst fem aktuella jämförbara objekt i samma område.', rentEffect: 'Minskar risken för överskattat kassaflöde.',
    banks: 'Jämför bankernas erbjudanden', banksAction: 'Begär preliminära erbjudanden från minst två långivare.', banksEffect: 'Visar realistisk belåning, ränta och dokumentkrav.',
    bankRange: 'Få en bankbedömning', bankRangeAction: 'Ange inkomst, bosättning och aktuella skulder.', bankRangeEffect: 'Hjälper till att precisera belåning, ränta och månadsbetalning.',
  },
}

export function investorAiFallbackText(locale) {
  return text[locale] || text.ru
}
