import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

async function readOrEmpty(url) {
  try { return await readFile(url, 'utf8') } catch { return '' }
}

const header = await readOrEmpty(new URL('./InvestorMobileStepHeader.jsx', import.meta.url))
const headerCss = await readOrEmpty(new URL('./InvestorMobileStepHeader.css', import.meta.url))
const result = await readOrEmpty(new URL('./InvestorMobileResultCard.jsx', import.meta.url))
const resultCss = await readOrEmpty(new URL('./InvestorMobileResultCard.css', import.meta.url))
const sourceHero = await readOrEmpty(new URL('./InvestorSourceHero.jsx', import.meta.url))
const sourceHeroCss = await readOrEmpty(new URL('./InvestorSourceHero.css', import.meta.url))
const goalFlow = await readOrEmpty(new URL('./InvestorGoalFlow.jsx', import.meta.url))
const goalFlowCss = await readOrEmpty(new URL('./InvestorGoalFlow.css', import.meta.url))
const assumptions = await readOrEmpty(new URL('./InvestorAssumptionsSheet.jsx', import.meta.url))
const assumptionsCss = await readOrEmpty(new URL('./InvestorAssumptionsSheet.css', import.meta.url))
const aiExperience = await readOrEmpty(new URL('./InvestorAiExperience.jsx', import.meta.url))
const aiExperienceCss = await readOrEmpty(new URL('./InvestorAiExperience.css', import.meta.url))
const aiService = await readOrEmpty(new URL('../../services/investorAiService.js', import.meta.url))
const page = await readOrEmpty(new URL('../../pages/InvestmentCalculator.jsx', import.meta.url))
const pageCss = await readOrEmpty(new URL('../../pages/InvestmentCalculator.css', import.meta.url))
const tiffanyButtonCss = await readOrEmpty(new URL('../../styles/tiffany-shine-button.css', import.meta.url))

test('mobile investor header explains the three-step decision path', () => {
  assert.match(header, /Объект/)
  assert.match(header, /Цель/)
  assert.match(header, /Результат/)
  assert.match(header, /aria-current/)
  assert.match(header, /progress/)
  assert.match(headerCss, /var\(--buyer-teal/)
})

test('mobile investor result separates deterministic outcome, assumptions and risk', () => {
  assert.match(result, /Базовый сценарий/)
  assert.match(result, /Ваш капитал/)
  assert.match(result, /Доходность/)
  assert.match(result, /yieldLabel/)
  assert.match(result, /Денежный поток/)
  assert.match(result, /Что учтено/)
  assert.match(result, /Риск/)
  assert.match(resultCss, /var\(--buyer-mint\)/)
})

test('calculator uses object-goal-result order across mobile and desktop', () => {
  assert.match(page, /useMobileLayout\(768\)/)
  assert.match(page, /InvestorMobileStepHeader/)
  assert.match(page, /InvestorMobileResultCard/)
  assert.match(page, /showSourceStep = wizardStep === 1/)
  assert.match(page, /showStrategyStep = wizardStep === 2/)
  assert.match(pageCss, /\.calc-mobile-sticky-action/)
  assert.match(pageCss, /padding-bottom:\s*calc\([^)]*safe-area-inset-bottom/)
})

test('mobile object and goal steps collect the minimum decision inputs before results', () => {
  assert.match(sourceHero, /investor-source-hero__manual-fields/)
  assert.match(sourceHero, /Цена покупки/)
  assert.match(sourceHero, /Ремонт и подготовка/)
  assert.match(sourceHero, /investor-source-hero__favorites-grid/)
  assert.match(sourceHero, /onPickFavorite/)
  assert.match(page, /InvestorGoalFlow/)
  assert.match(goalFlow, /stage === 'choose'/)
  assert.match(goalFlow, /Горизонт владения/)
  assert.match(goalFlow, /Расходы при покупке/)
  assert.match(goalFlow, /Ожидаемая аренда в год/)
  assert.match(page, /requiresRentalIncome/)
  assert.match(page, /Доходность за период/)
  assert.match(page, /Доходность в год/)
})

test('numeric investment inputs expose mobile keyboard and bounds', () => {
  assert.match(page, /inputMode="decimal"/)
  assert.match(goalFlow, /inputMode="numeric"/)
  assert.match(goalFlow, /inputMode="decimal"/)
  assert.match(page, /min="0"/)
  assert.match(page, /step="any"/)
})

test('goal selection uses swipeable cards before opening a separate values scene', () => {
  assert.match(goalFlow, /Выберите цель/)
  assert.match(goalFlow, /Сдавать в аренду/)
  assert.match(goalFlow, /Купить и перепродать/)
  assert.match(goalFlow, /Купить долю/)
  assert.match(goalFlow, /Параметры цели/)
  assert.match(goalFlow, /AnimatePresence/)
  assert.match(goalFlowCss, /scroll-snap-type:\s*x mandatory/)
  assert.match(goalFlowCss, /investor-goal-flow__goal-card--resale/)
  assert.match(goalFlowCss, /investor-goal-flow__fields/)
})

test('investor starts with a real property-card composition and transitions to two radio source choices', () => {
  assert.match(page, /InvestorSourceHero/)
  assert.match(sourceHero, /CURATED_PROPERTY_CARDS/)
  assert.doesNotMatch(sourceHero, /getPropertyCardImage/)
  assert.doesNotMatch(sourceHero, /favoriteItems\.forEach/)
  assert.match(sourceHero, /investor-source-hero__property-card/)
  assert.match(sourceHero, /investor-source-hero__property-action/)
  assert.match(sourceHero, /Рассчитать/)
  assert.match(sourceHero, /AnimatePresence/)
  assert.match(sourceHero, /hasStarted/)
  assert.match(sourceHero, /Начать/)
  assert.match(sourceHero, /Создайте лучшее будущее для себя/)
  assert.match(sourceHero, /type="radio"/)
  assert.match(sourceHero, /name="investor-source"/)
  assert.match(sourceHero, /Из понравившегося/)
  assert.match(sourceHero, /Свои значения/)
  assert.match(sourceHero, /onSelectFavorites/)
  assert.match(sourceHero, /onSelectManual/)
  assert.match(sourceHero, /setupMotion/)
  assert.match(sourceHero, /investor-source-hero__continue/)
  assert.doesNotMatch(page, /favoriteAuctions\[0\]/)
  assert.doesNotMatch(sourceHero, /smart-investor-logo-tile/)
  assert.doesNotMatch(sourceHero, /smart-investor-homes-network-v1/)
  assert.match(sourceHeroCss, /\.investor-source-hero__portfolio/)
  assert.match(sourceHeroCss, /investor-source-hero__property-card--amber/)
  assert.match(sourceHeroCss, /investor-source-hero__property-card--silver/)
  assert.match(sourceHeroCss, /investor-source-hero__property-card--sky/)
  assert.doesNotMatch(sourceHero, /investor-source-hero__pair-link/)
  assert.doesNotMatch(sourceHero, /investor-network-shape\.png/)
  assert.doesNotMatch(sourceHero, /investor-source-hero__doodle/)
  assert.match(sourceHeroCss, /object-fit:\s*cover/)
  assert.match(sourceHeroCss, /background:\s*#080909/)
  assert.match(sourceHeroCss, /background:\s*#ffffff/)
  assert.match(sourceHeroCss, /background:\s*#ff2d8a/)
  assert.match(sourceHeroCss, /font-family:\s*var\(--site-font-family/)
  assert.match(sourceHeroCss, /font-weight:\s*780/)
  assert.match(sourceHeroCss, /font:\s*800 17px\/1/)
  assert.doesNotMatch(sourceHeroCss, /smart-investor-word-highlight-v1\.png/)
  assert.doesNotMatch(sourceHero, /btn-tiffany-shine/)
  assert.match(tiffanyButtonCss, /#4ecdd6/i)
  assert.match(sourceHeroCss, /@media \(max-width:\s*768px\)/)
})

test('result keeps advanced assumptions in an accessible guided sheet on mobile', () => {
  assert.match(page, /InvestorAssumptionsSheet/)
  assert.match(page, /assumptionsOpen/)
  assert.match(page, /setAssumptionsOpen\(true\)/)
  assert.match(assumptions, /BuyerSheetShell/)
  assert.match(assumptions, /Параметры сценария/)
  assert.match(assumptions, /Расчёт обновляется сразу/)
  assert.match(assumptions, /Для персональной оценки/)
  assert.match(assumptions, /Чистый доход в месяц/)
  assert.match(page, /borrowerMonthlyIncome/)
  assert.match(assumptionsCss, /min-height:\s*var\(--buyer-touch\)/)
})

test('AI result provides a cinematic loader and a single focused score screen', () => {
  assert.match(page, /requestInvestorAiAnalysis/)
  assert.match(aiService, /\/investment\/ai-analysis/)
  assert.match(aiExperience, /Собираем рынок/)
  assert.match(aiExperience, /Строим сценарии/)
  assert.match(aiExperience, /Оцениваем ипотеку/)
  assert.match(aiExperience, /function FocusedResult/)
  assert.match(aiExperience, /setAnimatedScore/)
  assert.match(aiExperience, /scoreAnimationComplete/)
  assert.match(aiExperience, /SCORE_REVEAL_DURATION = 1350/)
  assert.match(aiExperience, /setScoreAnimationComplete\(true\)/)
  assert.match(aiExperience, /\{scoreAnimationComplete && \(/)
  assert.match(aiExperience, /requestAnimationFrame/)
  assert.match(aiExperience, /Оценка сделки/)
  assert.match(aiExperience, /Потенциальный результат/)
  assert.match(aiExperience, /Рост цены/)
  assert.match(aiExperience, /Арендная доходность/)
  assert.match(aiExperience, /Окупаемость/)
  assert.match(aiExperience, /AI-анализ/)
  assert.match(aiExperience, /analysis\?\.verdict\?\.headline/)
  assert.match(aiExperience, /analysis\?\.verdict\?\.summary/)
  assert.match(aiExperience, /function buildResultFactors/)
  assert.match(aiExperience, /Что формирует результат/)
  assert.match(aiExperience, /Цена входа/)
  assert.match(aiExperience, /Финансирование/)
  assert.match(aiExperience, /activeFactor/)
  assert.match(aiExperience, /function buildMarketOutcomeSummary/)
  assert.doesNotMatch(aiExperience, /baseStartValue/)
  assert.doesNotMatch(aiExperience, /Цена сейчас/)
  assert.match(aiExperience, /Три исхода рынка/)
  assert.match(aiExperience, /Осторожный/)
  assert.match(aiExperience, /Базовый/)
  assert.match(aiExperience, /Сильный/)
  assert.match(aiExperience, /MarketOutcomeChart/)
  assert.match(aiExperience, /function OutcomePriceMarker/)
  assert.doesNotMatch(aiExperience, /Старт ·/)
  assert.match(aiExperience, /showStart/)
  assert.match(aiExperienceCss, /investor-score-screen__chart-price-label/)
  assert.match(aiExperience, /function buildLiquiditySummary/)
  assert.match(aiExperience, /function buildCashFlowSummary/)
  assert.match(aiExperience, /index === points\.length - 1 \? '#55f4ff' : 'rgba\(132, 143, 145, 0\.72\)'/)
  assert.match(aiExperience, /drop-shadow\(0 0 8px rgba\(85, 244, 255, 0\.72\)\)/)
  assert.match(aiExperience, />Риски</)
  assert.match(aiExperience, />Ликвидность</)
  assert.match(aiExperience, />Денежный поток</)
  assert.match(aiExperience, /AI-рекомендации/)
  assert.match(aiExperience, />Ипотека</)
  assert.match(aiExperience, /Рассчитать заново/)
  assert.match(aiExperience, /На главную/)
  assert.match(aiExperience, /onRestart=\{onRestart \|\| onBack\}/)
  assert.match(page, /onRestart=\{resetWizard\}/)
  assert.match(page, /onHome=\{\(\) => navigate\('\/', \{ replace: true \}\)\}/)
  assert.match(aiExperience, /не является банковским одобрением/)
  assert.match(aiExperienceCss, /investor-ai-loader__flash/)
  assert.match(aiExperienceCss, /investor-ai-loader__ring/)
  assert.match(aiExperienceCss, /investor-ai-loader__orbit/)
  assert.match(aiExperience, /investor-ai-loader__ring-progress/)
  assert.match(aiExperience, /strokeDashoffset/)
  assert.match(aiExperienceCss, /investor-score-screen__gradient/)
  assert.match(aiExperienceCss, /--investor-tiffany:\s*#0099a9/)
  assert.match(aiExperienceCss, /--investor-tiffany-light:\s*#55f4ff/)
  assert.match(aiExperienceCss, /investor-score-screen__gradient[\s\S]*position:\s*fixed/)
  assert.match(aiExperienceCss, /investor-score-screen__gradient[\s\S]*z-index:\s*-1/)
  assert.match(aiExperienceCss, /radial-gradient\(ellipse 88% 96% at 112% 104%/)
  assert.match(aiExperienceCss, /radial-gradient\(ellipse 150% 62% at 50% 110%/)
  assert.match(aiExperienceCss, /linear-gradient\(180deg, #050606/)
  assert.match(aiExperienceCss, /investor-score-screen__row/)
  assert.match(aiExperienceCss, /investor-score-screen__analysis/)
  assert.match(aiExperienceCss, /investor-score-screen__factor-fill/)
  assert.doesNotMatch(aiExperienceCss, /factor\.is-negative \.investor-score-screen__factor-fill/)
  assert.match(aiExperienceCss, /investor-score-screen__factor-explanation/)
  assert.match(aiExperienceCss, /investor-score-screen__outcome-chart/)
  assert.doesNotMatch(aiExperienceCss, /investor-score-screen__outcome-range/)
  assert.doesNotMatch(aiExperienceCss, /investor-score-screen__outcome-line--/)
  assert.match(aiExperienceCss, /investor-score-screen__outcome-list/)
  assert.match(aiExperienceCss, /investor-score-screen__risk-list/)
  assert.match(aiExperienceCss, /investor-score-screen__liquidity-score/)
  assert.match(aiExperienceCss, /investor-score-screen__cash-chart/)
  assert.match(aiExperienceCss, /investor-score-screen__recommendation-list/)
  assert.match(aiExperienceCss, /investor-score-screen__mortgage-primary/)
  assert.match(aiExperienceCss, /investor-score-screen__actions/)
  assert.doesNotMatch(aiExperienceCss, /\.investor-score-screen__analysis\s*\{[^}]*border-top/)
  assert.doesNotMatch(aiExperienceCss, /\.investor-score-screen__factors\s*\{[^}]*border-top/)
  assert.doesNotMatch(aiExperienceCss, /\.investor-score-screen__outcomes\s*\{[^}]*border-top/)
  assert.doesNotMatch(aiExperienceCss, /\.investor-score-screen__detail-section\s*\{[^}]*border-top/)
  assert.doesNotMatch(aiExperienceCss, /\.investor-score-screen__actions\s*\{[^}]*border-top/)
  assert.match(aiExperienceCss, /\.investor-score-screen__analysis\s*\{[^}]*margin-top:\s*34px/)
  assert.match(aiExperienceCss, /\.investor-score-screen__factors\s*\{[^}]*margin-top:\s*48px/)
  assert.match(aiExperienceCss, /\.investor-score-screen__outcomes\s*\{[^}]*margin-top:\s*50px/)
  assert.match(aiExperienceCss, /\.investor-score-screen__detail-section\s*\{[^}]*margin-top:\s*50px/)
})

test('mobile result provides a real next property action without claiming guaranteed returns', () => {
  assert.match(result, /onOpenAssumptions/)
  assert.match(result, /onOpenProperty/)
  assert.match(result, /Среднее за месяц периода/)
  assert.doesNotMatch(result, /гарантирован/i)
  assert.match(resultCss, /min-height:\s*var\(--buyer-touch\)/)
})

test('phone layout is clipped to the viewport while desktop calculator remains untouched', () => {
  assert.match(pageCss, /overflow-x:\s*clip/)
  assert.match(pageCss, /\.calc-step3-sidebar\.calc-dashboard__form\s*\{[^}]*display:\s*none/s)
  assert.match(pageCss, /@media \(min-width:\s*769px\)/)
})
